module.exports = {
  tokenInvalid: "Authorization credentials (token) not valid",
  userRegister: "Register successfull",
  userLogin: "Login successfull",
  updateSuccess: "Updated successfull",
  validationErrors: "Validation Errors",
  incorrectPassword: "Password is not correct",
  serverError: "Internal server error",
  emailAlreadyExist: "User already exist",
  notFound: "User not found",
  tokenRegistered: "User app token registered",
  logout: "Logged out sccessfully",
  found: "Users found sccessfully",
  unauthorized: "You are not authorized to perform this action.",
  tokenNotFound: "No Authorization header found or wrong format",
};
